language: csharp

dotnet: 3.1.301
mono: none
sudo: false

git:
   depth: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
        - CODECOV_TOKEN="030b932b-3989-4b6f-91ce-b70a152bb005"

addons:
  sonarcloud:
    organization: "bookcrossing-softserve"
    
before_script:
    - ./tools/travis-ci-install-sonar.sh

script:
    - dotnet build src/BookCrossingBackEnd.sln -c Release
    - dotnet test -c Release --no-build src/ApplicationTest/ApplicationTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - dotnet ../tools/sonar/SonarScanner.MSBuild.dll begin /o:"bookcrossing-softserve" /k:"BookCrossing-SoftServe_Bookcrossing-Back-End" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.verbose=true /d:sonar.login=${SONAR_TOKEN}
    - dotnet ../tools/sonar/SonarScanner.MSBuild.dll end /d:sonar.login=${SONAR_TOKEN}

after_script:
    - bash <(curl -s https://codecov.io/bash) 

deploy:
    provider: azure_web_apps
    verbose: true
    on:
        develop
