version: '3'
services:
  api:
    build: .
    container_name: api
    environment:
      ConnectionStrings:DefaultConnection: "Server=mssqldb,1433;Database=BookCrossing;User Id=SA;Password=P@ssw0rd;Trusted_Connection=False;MultipleActiveResultSets=true"
      MongoSettings:ConnectionString: "mongodb://mongodb:27017"
      MongoSettings:DatabaseName: "BookCrossingDB"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - mssqldb
    entrypoint: ["/wait-for-it.sh", "mssqldb:1433", "-t", "120", "--", "dotnet", "BookCrossingBackEnd.dll"]
    networks:
      - backend
  mongodb:
    image: "mongo:4.2.8"
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
  mssqldb:
    image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
    container_name: mssqldb
    volumes:
      - mssqldbdata:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
    ports:
      - "1433:1433"
    networks:
      - backend
networks:
  backend:
volumes:
  mongodbdata:
  mssqldbdata:
